version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi
    expose:
      - "8000"
    environment:
      - DATABASE_URL=sqlite:///./blog.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost/api

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
